# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[key-mapping.key-notation-to-key-code]
mod = 'alt-cmd'
mod2 = 'alt-cmd-ctrl'

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
alt-enter = '''exec-and-forget osascript -e '
tell application "Terminal"
    do script
    activate
end tell'
'''

# i3 wraps focus by default
mod-h = 'focus --boundaries-action wrap-around-the-workspace left'
mod-j = 'focus --boundaries-action wrap-around-the-workspace down'
mod-k = 'focus --boundaries-action wrap-around-the-workspace up'
mod-l = 'focus --boundaries-action wrap-around-the-workspace right'

mod2-h = 'move left'
mod2-j = 'move down'
mod2-k = 'move up'
mod2-l = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
mod-backslash = 'split horizontal'
mod-minus = 'split vertical'

mod-f = 'fullscreen'

mod-s = 'layout v_accordion'               # 'layout stacking' in i3
mod-w = 'layout h_accordion'               # 'layout tabbed' in i3
mod-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

mod2-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

mod-1 = 'workspace 1'
mod-2 = 'workspace 2'
mod-3 = 'workspace 3'
mod-4 = 'workspace 4'
mod-5 = 'workspace 5'
mod-6 = 'workspace 6'
mod-7 = 'workspace 7'
mod-8 = 'workspace 8'
mod-9 = 'workspace 9'
mod-0 = 'workspace 10'

mod2-1 = 'move-node-to-workspace 1'
mod2-2 = 'move-node-to-workspace 2'
mod2-3 = 'move-node-to-workspace 3'
mod2-4 = 'move-node-to-workspace 4'
mod2-5 = 'move-node-to-workspace 5'
mod2-6 = 'move-node-to-workspace 6'
mod2-7 = 'move-node-to-workspace 7'
mod2-8 = 'move-node-to-workspace 8'
mod2-9 = 'move-node-to-workspace 9'
mod2-0 = 'move-node-to-workspace 10'

mod2-c = 'reload-config'

mod-r = 'mode resize'

mod2-o = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
