{ inputs, ... }@flakeContext:
{ config, lib, pkgs, ... }: {
  config = {
    environment = {
      systemPackages = [
        pkgs.luajit
        pkgs.lua53Packages.lua
        pkgs.lua53Packages.libluv
        pkgs.lua53Packages.lua5.3-argparse
        pkgs.lua53Packages.lua5.3-busted
        pkgs.lua53Packages.lua5.3-busted-htest
        pkgs.lua53Packages.lua5.3-commons.nvim
        pkgs.lua53Packages.lua5.3-compat53
        pkgs.lua53Packages.lua5.3-cosmo
        pkgs.lua53Packages.lua5.3-ldoc
        pkgs.lua53Packages.lua5.3-http
        pkgs.lua53Packages.lua5.3-image.nvim
        pkgs.lua53Packages.lua5.3-inspect
        pkgs.lua53Packages.lua5.3-jsregexp
        pkgs.lua53Packages.lua5.3-lua-lsp
        pkgs.lua53Packages.lua5.3-lua-utils.nvim
        pkgs.lua53Packages.lua5.3-luacheck
        pkgs.lua53Packages.lua5.3-luarocks
        pkgs.lua53Packages.lua5.3-luarocks-build-rust-mlua
        pkgs.lua53Packages.lua5.3-luarocks-build-treesitter-parser
        pkgs.lua53Packages.lua5.3-luasnip
        pkgs.lua53Packages.lua5.3-luasql-sqlite3
        pkgs.lua53Packages.lua5.3-luassert
        pkgs.lua53Packages.lua5.3-luasystem
        pkgs.lua53Packages.lua5.3-luatext
        pkgs.lua53Packages.lua5.3-luaunit
        pkgs.lua53Packages.lua5.3-luautf8
        pkgs.lua53Packages.lua5.3-luazip
        pkgs.lua53Packages.lua5.3-luuid
        pkgs.lua53Packages.lua5.3-luv
        pkgs.lua53Packages.lua5.3-lyaml
        pkgs.lua53Packages.lua5.3-markdown
        pkgs.lua53Packages.lua5.3-madiator_lua
        pkgs.lua53Packages.lua5.3-middleclass
        pkgs.lua53Packages.lua5.3-neorg
        pkgs.lua53Packages.lua5.3-neotest
        pkgs.lua53Packages.lua5.3-nlua
        pkgs.lua53Packages.lua5.3-nui.nvim
        pkgs.lua53Packages.lua5.3-nvim-cmp-scm
        pkgs.lua53Packages.lua5.3-nvim-nio
        pkgs.lua53Packages.lua5.3-pathlib.nvim
        pkgs.lua53Packages.lua5.3-penlight
        pkgs.lua53Packages.lua5.3-plenary.nvim-scm
        pkgs.lua53Packages.lua5.3-readline
        pkgs.lua53Packages.lua5.3-rest.nvim
        pkgs.lua53Packages.lua5.3-rocks-config.nvim
        pkgs.lua53Packages.lua5.3-rocks-dev.nvim
        pkgs.lua53Packages.lua5.3-rocks-git.nvim
        pkgs.lua53Packages.lua5.3-rocks.nvim
        pkgs.lua53Packages.lua5.3-rtp.nvim
        pkgs.lua53Packages.lua5.3-say
        pkgs.lua53Packages.lua5.3-serpent
        pkgs.lua53Packages.lua5.3-std._debug
        pkgs.lua53Packages.lua5.3-std.normalize
        pkgs.lua53Packages.lua5.3-stdlib
      ];
    };
  };
}
