{ inputs, ... }@flakeContext:
{ config, lib, pkgs, ... }: {
  config = {
    environment = {
      systemPackages = [
        pkgs.luajit
        pkgs.lua53Packages.lua
        pkgs.lua53Packages.libluv
        pkgs.lua53Packages.lua5_3-argparse
        pkgs.lua53Packages.lua5_3-busted
        pkgs.lua53Packages.lua5_3-busted-htest
        pkgs.lua53Packages.lua5_3-commons.nvim
        pkgs.lua53Packages.lua5_3-compat53
        pkgs.lua53Packages.lua5_3-cosmo
        pkgs.lua53Packages.lua5_3-ldoc
        pkgs.lua53Packages.lua5_3-http
        pkgs.lua53Packages.lua5_3-image.nvim
        pkgs.lua53Packages.lua5_3-inspect
        pkgs.lua53Packages.lua5_3-jsregexp
        pkgs.lua53Packages.lua5_3-lua-lsp
        pkgs.lua53Packages.lua5_3-lua-utils.nvim
        pkgs.lua53Packages.lua5_3-luacheck
        pkgs.lua53Packages.lua5_3-luarocks
        pkgs.lua53Packages.lua5_3-luarocks-build-rust-mlua
        pkgs.lua53Packages.lua5_3-luarocks-build-treesitter-parser
        pkgs.lua53Packages.lua5_3-luasnip
        pkgs.lua53Packages.lua5_3-luasql-sqlite3
        pkgs.lua53Packages.lua5_3-luassert
        pkgs.lua53Packages.lua5_3-luasystem
        pkgs.lua53Packages.lua5_3-luatext
        pkgs.lua53Packages.lua5_3-luaunit
        pkgs.lua53Packages.lua5_3-luautf8
        pkgs.lua53Packages.lua5_3-luazip
        pkgs.lua53Packages.lua5_3-luuid
        pkgs.lua53Packages.lua5_3-luv
        pkgs.lua53Packages.lua5_3-lyaml
        pkgs.lua53Packages.lua5_3-markdown
        pkgs.lua53Packages.lua5_3-madiator_lua
        pkgs.lua53Packages.lua5_3-middleclass
        pkgs.lua53Packages.lua5_3-neorg
        pkgs.lua53Packages.lua5_3-neotest
        pkgs.lua53Packages.lua5_3-nlua
        pkgs.lua53Packages.lua5_3-nui.nvim
        pkgs.lua53Packages.lua5_3-nvim-cmp-scm
        pkgs.lua53Packages.lua5_3-nvim-nio
        pkgs.lua53Packages.lua5_3-pathlib.nvim
        pkgs.lua53Packages.lua5_3-penlight
        pkgs.lua53Packages.lua5_3-plenary.nvim-scm
        pkgs.lua53Packages.lua5_3-readline
        pkgs.lua53Packages.lua5_3-rest.nvim
        pkgs.lua53Packages.lua5_3-rocks-config.nvim
        pkgs.lua53Packages.lua5_3-rocks-dev.nvim
        pkgs.lua53Packages.lua5_3-rocks-git.nvim
        pkgs.lua53Packages.lua5_3-rocks.nvim
        pkgs.lua53Packages.lua5_3-rtp.nvim
        pkgs.lua53Packages.lua5_3-say
        pkgs.lua53Packages.lua5_3-serpent
        pkgs.lua53Packages.lua5_3-std._debug
        pkgs.lua53Packages.lua5_3-std.normalize
        pkgs.lua53Packages.lua5_3-stdlib
      ];
    };
  };
}
