name: Update Flakes
on:
  schedule:
    - cron: 12 */1 * * *
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  # configure:
  #   runs-on: x86_64-linux
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   steps:
  #     - name: Checkout repository for Install
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Install Determinate Nix
  #       uses: DeterminateSystems/nix-installer-action@main
  #     - name: Install Omnix
  #       run: nix --accept-flake-config profile install "github:juspay:omnix"
  #     - id: set-matrix
  #       run: |
  #         set -euxo pipefail
  #         MATRIX="$(om ci gh-matrix --systems=x86_64-linux,aarch64-darwin | jq -c .)"
  #         echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  update-packages:
    if: github.ref_name == github.event.repository.default_branch
    # runs-on: ${{ matrix.os }}
    # needs: configure
    strategy:
      # matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository for Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix with Cachix
        uses: cachix/install-nix-action@v26

      - name: Update Flakes
        run: nix flake update --accept-flake-config

      - name: Install Omnix
        run: nix --accept-flake-config profile install github:juspay/omnix

      - name: Authenticate Cachix
        uses: cachix/cachix-action@v14
        with:
          name: saberzero1
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          installCommand: nix profile install --accept-flake-config nixpkgs#cachix

      - name: Test Flakes
        run: nix flake check

      # - name: Build Flakes
      #   run: nix run .#activate --accept-flake-config

      - name: Omnix deploy to Cachix
        run: om ci run --include-all-dependencies -- --accept-flake-config | xargs cachix push saberzero1

      - name: Push changes
        if: runner.os == 'Linux'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: flake.lock
          skip_fetch: false
          skip_dirty_check: false
          skip_checkout: false
          commit_message: "[ci] flakes: auto-updated"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
